-- =============================================================================
-- IMAGES — where they live, how to inspect them, how to replace them.
--
-- Paste the whole file into the Supabase SQL editor and run it: everything
-- above the RECIPES line is read-only and prints a report.
--
-- The recipes below that line are COMMENTED OUT on purpose. Copy the one you
-- want into a new query, edit it, and run that. Nothing here changes data
-- unless you deliberately uncomment it.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- WHERE IMAGES COME FROM
--
--   Table            public.product_images   (defined in 0003_catalog.sql)
--   Seeded by        supabase/seed.sql, two rows per product
--   Read by          the product_cards view (0007), which picks ONE image per
--                    product: `order by is_primary desc, position limit 1`
--   Files            public/images/products/<slug>-1.svg and -2.svg,
--                    generated by `npm run images`
--
-- The URL is just text. Nothing in the application cares whether it points at
-- a local SVG, Supabase Storage, or a CDN — which is why swapping in real
-- photography is a data change, not a code change.
-- -----------------------------------------------------------------------------

-- 1. What does each product actually have?
select
  p.slug,
  count(pi.id)                                   as images,
  count(*) filter (where pi.is_primary)          as primary_images,
  min(pi.url) filter (where pi.is_primary)       as primary_url
from products p
left join product_images pi on pi.product_id = p.id
group by p.slug
order by images, p.slug;

-- 2. Anything broken? These three should all return zero rows.
select 'no image at all' as problem, p.slug
  from products p
 where not exists (select 1 from product_images pi where pi.product_id = p.id)
union all
select 'no primary image', p.slug
  from products p
 where exists (select 1 from product_images pi where pi.product_id = p.id)
   and not exists (select 1 from product_images pi where pi.product_id = p.id and pi.is_primary)
union all
select 'empty alt text', p.slug
  from products p
  join product_images pi on pi.product_id = p.id
 where coalesce(trim(pi.alt), '') = '';

-- 3. Duplicates. Should be zero after fix-duplicates.sql.
select p.slug, pi.url, count(*) as copies
  from product_images pi
  join products p on p.id = pi.product_id
 group by p.slug, pi.url
having count(*) > 1
 order by copies desc;

-- 4. Every image row, in the order the storefront sees them.
select p.slug, pi.position, pi.is_primary, pi.url, pi.width, pi.height, pi.alt
  from product_images pi
  join products p on p.id = pi.product_id
 order by p.slug, pi.is_primary desc, pi.position;


-- =============================================================================
-- RECIPES — everything below is commented out. Copy, edit, run separately.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- A. Replace the main photograph of ONE product.
--    Upload the file to Supabase Storage first (a public bucket called
--    `product-images`), then paste its public URL here.
-- -----------------------------------------------------------------------------
-- update product_images
--    set url    = 'https://YOUR-PROJECT.supabase.co/storage/v1/object/public/product-images/overcoat-front.jpg',
--        alt    = 'Obsidian cashmere overcoat photographed front-on',
--        width  = 1600,
--        height = 2000
--  where is_primary
--    and product_id = (select id from products where slug = 'obsidian-cashmere-overcoat');

-- -----------------------------------------------------------------------------
-- B. Add an extra photograph to a product (a third angle, a detail).
--    `position` orders the gallery after the primary image.
-- -----------------------------------------------------------------------------
-- insert into product_images (product_id, url, alt, width, height, position, is_primary)
-- select id,
--        'https://YOUR-PROJECT.supabase.co/storage/v1/object/public/product-images/overcoat-back.jpg',
--        'Obsidian cashmere overcoat from behind',
--        1600, 2000, 2, false
--   from products where slug = 'obsidian-cashmere-overcoat'
-- on conflict (product_id, url) do nothing;

-- -----------------------------------------------------------------------------
-- C. Swap EVERY product over to a storage bucket in one statement.
--    Assumes you uploaded files named exactly like the slugs: <slug>-1.jpg.
--    Run the SELECT first to see what it would do.
-- -----------------------------------------------------------------------------
-- select p.slug, pi.url as old_url,
--        'https://YOUR-PROJECT.supabase.co/storage/v1/object/public/product-images/'
--          || p.slug || '-1.jpg' as new_url
--   from product_images pi join products p on p.id = pi.product_id
--  where pi.is_primary;
--
-- update product_images pi
--    set url = 'https://YOUR-PROJECT.supabase.co/storage/v1/object/public/product-images/'
--              || p.slug || '-1.jpg'
--   from products p
--  where p.id = pi.product_id and pi.is_primary;

-- -----------------------------------------------------------------------------
-- D. Put the generated SVGs back. Undoes A and C.
--
--    Two statements, not one. A single statement that set every non-primary
--    row to '<slug>-2.svg' collides on product_images_product_url_key the
--    moment a product has three images — which is exactly what recipe B does.
--    These restore the two seeded plates and leave anything you added alone.
-- -----------------------------------------------------------------------------
-- update product_images pi
--    set url = '/images/products/' || p.slug || '-1.svg'
--   from products p
--  where p.id = pi.product_id and pi.is_primary;
--
-- update product_images pi
--    set url = '/images/products/' || p.slug || '-2.svg'
--   from products p
--  where p.id = pi.product_id and not pi.is_primary and pi.position = 1;
--
--    To go back to exactly two images per product, delete the extras first:
-- delete from product_images where position > 1;

-- -----------------------------------------------------------------------------
-- E. Fix a product that has no primary image, or more than one.
--    A partial unique index allows only one primary per product, so clear
--    them all first and then set exactly one.
-- -----------------------------------------------------------------------------
-- update product_images set is_primary = false
--  where product_id = (select id from products where slug = 'PRODUCT-SLUG');
--
-- update product_images set is_primary = true
--  where id = (
--    select id from product_images
--     where product_id = (select id from products where slug = 'PRODUCT-SLUG')
--     order by position limit 1
--  );

-- -----------------------------------------------------------------------------
-- F. Category, banner and journal imagery live on their own tables.
-- -----------------------------------------------------------------------------
-- update categories  set image_url = '...' , image_alt = '...'          where slug = 'outerwear';
-- update banners     set image_url = '...' , image_alt = '...'          where placement = 'HOME_HERO';
-- update blog_posts  set featured_image_url = '...', featured_image_alt = '...' where slug = 'eleven-hours';
-- update story_sections set image_url = '...', image_alt = '...'        where key = 'atelier';

-- -----------------------------------------------------------------------------
-- REMEMBER: next/image only loads remote hosts listed in next.config.mjs, and
-- it does NOT fail quietly — an unlisted host throws and takes the whole page
-- down with it. Currently allowed: your own Supabase Storage bucket, and
-- images.unsplash.com. Add any other CDN there BEFORE putting its URLs in the
-- database.
-- -----------------------------------------------------------------------------
