import manifest from "@/public/images/og/manifest.json";

/**
 * Which image a page hands to a social platform.
 *
 * Three rules, in order:
 *   1. An explicit `og_image_url` from the CMS always wins — that is the point
 *      of the field.
 *   2. Otherwise a generated 1200x630 card, if one exists for this slug.
 *   3. Otherwise the brand card.
 *
 * **Never an SVG.** No major platform renders one: X, Facebook, LinkedIn,
 * Slack and WhatsApp all drop the image entirely, and it fails silently until
 * somebody shares the page. The product plates on the site are SVG on purpose;
 * these cards are PNG for the same reason.
 *
 * The manifest is generated by `npm run images`, so a product added through
 * the admin after the last run correctly falls back to the brand card rather
 * than pointing at a 404.
 */

export const OG_DEFAULT = "/images/og/default.png";

export const OG_DIMENSIONS = { width: 1200, height: 630 } as const;

const products = new Set(manifest.products);
const categories = new Set(manifest.categories);

export interface OgImage {
  url: string;
  width: number;
  height: number;
  alt: string;
}

function card(url: string, alt: string): OgImage {
  return { url, ...OG_DIMENSIONS, alt };
}

export function defaultOgImage(alt: string): OgImage {
  return card(OG_DEFAULT, alt);
}

export function productOgImage(
  slug: string,
  name: string,
  override?: string | null
): OgImage {
  if (override) return card(override, name);
  return card(
    products.has(slug) ? `/images/og/product-${slug}.png` : OG_DEFAULT,
    name
  );
}

export function categoryOgImage(
  slug: string,
  name: string,
  override?: string | null
): OgImage {
  if (override) return card(override, name);
  return card(
    categories.has(slug) ? `/images/og/category-${slug}.png` : OG_DEFAULT,
    name
  );
}

/** Journal and CMS pages have no generated card of their own yet. */
export function contentOgImage(title: string, override?: string | null): OgImage {
  return card(override || OG_DEFAULT, title);
}
